// importa metadados
import type { Metadata } from "next";

// importa o css
import "./globals.css";

// import font
import { Poppins } from "next/font/google";

// cria instancia da fonte
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import Header
import Header from "@/app/components/Header";

// import Auth Provider
import AuthProvider from "./provider/SessionProvider";

// layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
